spring.main.web-application-type=none
spring.main.banner-mode=off
spring.flyway.enabled=true
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.flyway.url=${MIGRATION_DATABASE_URL:${DATABASE_URL}}
spring.flyway.user=${MIGRATION_DATABASE_USERNAME}
spring.flyway.password=${MIGRATION_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
app.migration=true
app.scheduling.enabled=false
dispatch.maintenance.enabled=false
outbox.dispatcher.enabled=false
