spring.application.name=cab-marketplace

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/cab}
spring.datasource.username=${DATABASE_USERNAME:cab}
spring.datasource.password=${DATABASE_PASSWORD:cab}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.flyway.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.repositories.enabled=false
