logging.structured.format.console=logstash
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.flyway.user=${MIGRATION_DATABASE_USERNAME}
spring.flyway.password=${MIGRATION_DATABASE_PASSWORD:}
payments.fake.webhook-secret=${FAKE_PAYMENT_WEBHOOK_SECRET}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWK_SET_URI}
