CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE cities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE cabs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id varchar(255) NOT NULL,
    cab_number varchar(255),
    status varchar(255) NOT NULL,
    type varchar(255),
    locationx integer,
    locationy integer,
    idle_from bigint,
    city_id integer,
    model varchar(255)
);

CREATE INDEX idx_cabs_city_status ON cabs (city_id, status);
CREATE INDEX idx_cabs_driver ON cabs (driver_id);

CREATE TABLE bookings (
    booking_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time timestamp,
    end_time timestamp,
    rider_id varchar(255),
    cab_id integer NOT NULL,
    status varchar(255),
    start_location_x integer,
    start_location_y integer,
    end_location_x integer,
    end_location_y integer,
    booked_by varchar(255)
);

CREATE INDEX idx_bookings_cab ON bookings (cab_id);
CREATE INDEX idx_bookings_status_start_time ON bookings (status, start_time);

CREATE TABLE riders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id varchar(255) NOT NULL UNIQUE,
    name varchar(255),
    email varchar(255),
    phone_number varchar(255),
    photo_url varchar(255),
    current_location_x integer,
    current_location_y integer,
    home_x integer,
    home_y integer,
    work_x integer,
    work_y integer
);

CREATE TABLE idempotency_keys (
    key_value varchar(255) PRIMARY KEY,
    booking_id integer
);
