CREATE ROLE cab_app LOGIN PASSWORD 'cab-app-test' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
GRANT CONNECT ON DATABASE cab TO cab_app;
GRANT USAGE ON SCHEMA public TO cab_app;
ALTER DEFAULT PRIVILEGES FOR ROLE cab IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cab_app;
ALTER DEFAULT PRIVILEGES FOR ROLE cab IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO cab_app;
